### PR TITLE
Possible fixes?

### PR DESCRIPTION
**Pull request by wxmerkt**
Hi!
Thank you so much for creating this awesome plug-in! Unlike with the fontawesome-svg, I had some issues with the academicons on my local installation (ruby 2.7). I wonder if these changes are required or if I made a mistake initially configuring the plug-in?

### CODE REVIEW

**Comment by wxmerkt** [comment]
While I can get it to run now, the generated icons have the wrong `viewbox` (Twitter icon per jekyll-fontawesome-svg):
image

I might be doing something wrong here? (Red box added in CSS to visualise the rendered SVG)

Separately, I had a look at upgrading academicons.svg to the latest release but the regex expressions would need replacing, and are changing: Sometimes a horizontal offset (`horizontal-adv-x`), at other times it doesn't. 

Many thanks for any insights!

**Comment by sylvainmetayer** [comment]
Hi and thanks a lot for your contribution !

This is indeed a copy paste mistake, I'll merge this and make a new release today or tomorrow.

> While I can get it to run now, the generated icons have the wrong `viewbox`

> I had a look at upgrading academicons.svg to the latest release but the regex expressions would need replacing, and are changing: Sometimes a horizontal offset (`horizontal-adv-x`), at other times it doesn't.

I'm not using this anymore (I don't use Jekyll anymore) and I'm not a css expert. If you want to submit a MR, I can take a look at it and release. I might take a look at the academicons upgrade but I won't promise anything.

**Comment by sylvainmetayer** [comment]
https://rubygems.org/gems/jekyll-academicons-svg/versions/0.1.2 released which contains the fix

**Comment by wxmerkt** [comment]
Thank you very much for the quick merge and release. It appears that fixing the issue would be replacing regex with a XML parser to get the attributes -- I don't have the bandwidth to experiment on this right now and resorted to using the fonts directly for Academicons for now.

**Comment by LoicGrobol** [comment]
@sylvainmetayer Rather than changing the CSS, something that might work is to use the same approach as <https://github.com/sylvainmetayer/jekyll-fontawesome-svg> and use [the individual svg files](https://github.com/jpswalsh/academicons/tree/master/svg) rather than the big svg font. I can try to do a PR that but I am afraid I don't really know where to start :-)

**Comment by sylvainmetayer** [comment]
@LoicGrobol Thanks for the suggestion, this could be a better way to handle these icons ! 

The idea would be to put the icons in a dedicated folder and use the same method that is used in https://github.com/sylvainmetayer/jekyll-fontawesome-svg/blob/master/lib/jekyll/fontawesome/svg/fa-icon.rb#L40 

This should do it, don't hesitate to ping me if you need help with your PR

**Pull request merged**
